app:
  build: back
  ports:
    - 9000:9000
  links:
    - db:mongo
  environment:
    - MONGO_CONNECTION_STRING=mongodb://mongo:27017/sample
  entrypoint:
    - /usr/local/activator/activator
    - test


db:
  image: mongo:3.1.8
  ports:
    - 28017:27017
